version: 2

sources:
     - name: DBT_EXE
       database: SNOWFLAKE_SAMPLE_DATA 
       schema: TPCH_SF1
       tables: 
          - name: CUSTOMER
          - name: orders
          - name: part
